language: python
python:
  - 3.4
  - 3.5

install:
  - pip install --upgrade pip
  - pip install coveralls
  - pip install -r requirements-dev.txt

script:
  py.test --cov=aiohttp_jinja2 tests
after_success:
  coveralls

env:
  matrix:
    - PYTHONASYNCIODEBUG=x
    - PYTHONASYNCIODEBUG=
